scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: /metrics
  - job_name: 'circuitbreaker'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: /breaker
