repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # A versão foi atualizada para uma mais recente e estável.
    rev: v0.5.0
    hooks:
      - id: ruff
        # O --fix corrige automaticamente o que for possível, incluindo a
        # ordenação de imports (substituindo o isort).
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        # Este hook substitui o black para formatação de código.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-redis"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 582b9c66e0791980685c8b80bb11e6a3df1a06ef
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
