services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      LOG_LEVEL: DEBUG
    depends_on:
      - redis
      - db
    healthcheck:
      test: ["CMD", "curl", "--fail", "-I", "http://localhost:8000/health/glpi"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      # (opcional, você pode sobrescrever aqui)
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER_FILE: ${DB_USER_FILE:-}
      DB_PASSWORD_FILE: ${DB_PASSWORD_FILE:-}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
