name: glpi_dashboard_cau
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      LOG_LEVEL: DEBUG
    depends_on:
      - redis
      - db
    # Healthcheck incorporado na imagem

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    restart: always

  frontend:
    build:
      context: .
      dockerfile: src/frontend/react_app/Dockerfile
    depends_on:
      - backend
    env_file:
      - ./src/frontend/react_app/.env
    environment:
      # (opcional, você pode sobrescrever aqui)
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER_FILE: ${DB_USER_FILE:-}
      DB_PASSWORD_FILE: ${DB_PASSWORD_FILE:-}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
    # Healthcheck definido no Dockerfile

volumes:
  db_data:
