services:
  backend:
    command: python worker.py --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_PLAYWRIGHT=true
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/glpi"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"  # Porta padrão do Vite
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    working_dir: /app/frontend
    command: npm run dev

volumes:
  redis_data:
