services:
  backend:
    build: .
    command: python worker.py
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_PLAYWRIGHT=true
      - DB_HOST=db.prod
      - DB_PORT=5432
      - DB_NAME=app
      - DB_USER_FILE=/run/secrets/db_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    secrets:
      - db_user
      - db_password

  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://api.seudominio.com
    ports:
      - "80:3000"
    command: npm run build && npm run start

networks:
  default:
    external: true

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
