version: '3.9'
services:
  backend:
    build: .
    command: uvicorn worker:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file: .env
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    env_file: ./frontend/.env
    ports:
      - '3000:3000'
  db:
    image: postgres:15
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
