services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: glpi_dashboard
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  initdb:
    build: .
    command: python scripts/init_db.py
    env_file:
      - .env
    depends_on:
      - postgres

  worker:
    build: .
    command: python worker.py
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - initdb
      - redis

  dash:
    build: .
    command: python main.py
    env_file:
      - .env
    ports:
      - "8050:8050"
    depends_on:
      - initdb
      - redis

volumes:
  postgres_data:
  redis_data:
