services:
  backend:
    # Overrides the default command to run the development server with live-reloading.
    command: uvicorn backend.api.worker_api:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_PLAYWRIGHT=true
      - PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright
      - PYTHONPATH=/app/src
    # Mounts local source code into the container for live-reloading.
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

  frontend:
    build:
      context: .
      dockerfile: src/frontend/react_app/Dockerfile
      target: dev  # Usa o estágio de desenvolvimento
    ports:
      - "5174:5174"  # Porta customizada do Vite
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    volumes:
      # Mounts local source code for live-reloading, and uses a named volume
      # to persist node_modules, preventing it from being overwritten by the host.
      - ./src/frontend/react_app:/app:delegated
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5174

  db:
    ports:
      - "${HOST_DB_PORT:-55432}:5432"

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:v2.54.0
    platform: linux/amd64
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=warn"
    volumes:
      - ./resources/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_LOG_LEVEL=warn
      - GF_PLUGINS_BACKGROUNDINSTALLER_DISABLED=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=${GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS:-}
      - GF_DATABASE_SQLITE_ENABLE_WAL=true
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - prometheus

volumes:
  redis_data:
  frontend_node_modules:
  grafana_data:
