services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    command: python worker.py
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_PLAYWRIGHT=true
      - PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app
      - DB_USER_FILE=/run/secrets/db_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    secrets:
      - db_user
      - db_password
    depends_on:
      - db

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://ppiratini.intra.rs.gov.br/glpi/apirest.php
    ports:
      - "80:3000"
    command: npm run build && npm run start

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d:ro
    secrets:
      - db_user
      - db_password

networks:
  default:
    external: true

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password

volumes:
  db_data:
