services:
  backend:
    build: .
    command: uvicorn src.glpi_dashboard.services.worker_api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    env_file: .env
    environment:
      PYTHONPATH: /app/src
    depends_on:
      - db
      - redis
    ports:
      - "8001:8000"
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file: ./frontend/.env
    ports:
      - '3000:3000'
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      # use the same username defined in POSTGRES_USER
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - backend
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
volumes:
  db_data:
