services:
  backend:
    command: python worker.py --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_PLAYWRIGHT=true
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8000/health/glpi"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - ./.env

  frontend:
    build:
      context: ./src/frontend/react_app
      # sobrescreve o comando de instalação só neste serviço de dev:
      args:
        INSTALL_DEV_DEPS: "true"
    env_file: ./src/frontend/react_app/.env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"  # Porta padrão do Vite
    volumes:
      - ./src/frontend/react_app:/app/frontend
    working_dir: /app/frontend
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    ports:
      - "55432:5432"

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:v2.54.0
    platform: linux/amd64
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=warn"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_LOG_LEVEL=warn
      - GF_PLUGINS_BACKGROUNDINSTALLER_DISABLED=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=${GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS:-}
      - GF_DATABASE_SQLITE_ENABLE_WAL=true
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - prometheus

volumes:
  redis_data:
