services:
  backend:
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_PLAYWRIGHT=true
    volumes:
      - ./src:/app/src

  frontend:
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"  # Porta padrão do Vite
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    command: npm run dev
