[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "glpi-dashboard-cau"
version = "0.1.0"
description = "Service desk dashboard for GLPI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash>=2.17",
    "pandas>=2.2",
    "requests>=2.32",
    "python-dotenv>=1.0",
    "fastapi>=0.110",
    "uvicorn>=0.29",
    "strawberry-graphql>=0.223",
    "httpx>=0.27",
    "rich-click>=1.6",
    "aiohttp",
    "APScheduler",
    "SQLAlchemy==2.0.30",
    "asyncpg",
    "redis",
    "Flask-Caching>=2.1",
    "flask-compress",
    "langgraph>=0.0.22",
    "gql[httpx]>=3.5",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
