# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Verificar Checklist

"on":
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || "";
            if (body.includes('- [ ]')) {
              const {owner, repo} = context.repo;
              const issue_number = pr.number;
              const comments = await github.rest.issues.listComments({owner, repo, issue_number});
              const alreadyCommented = comments.data.some(c => c.user.type === 'Bot' && c.body.includes('Checklist incompleto'));
              if (!alreadyCommented) {
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number,
                  body: 'Checklist incompleto'
                });
              }
            }
