# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yaml-language-server: $disableComments=true
name: Contract Testing

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  workflow_call:
    secrets:
      PACT_BROKER_BASE_URL:
        required: true
      PACT_BROKER_TOKEN:
        required: true

jobs:
  consumer_tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/react_app/package-lock.json
      - name: Install dependencies
        run: |
          cd src/frontend/react_app
          npm install
      - name: Run consumer contract tests
        run: |
          cd src/frontend/react_app
          npm test -- --runTestsByPath tests/contracts/glpi-consumer.pact.js
      - name: Publish pacts
        env:
          PACT_BROKER_BASE_URL: '${{ secrets.PACT_BROKER_BASE_URL }}'
          PACT_BROKER_TOKEN: '${{ secrets.PACT_BROKER_TOKEN }}'
        run: |
          cd src/frontend/react_app
          npx pact-broker publish pacts \
            --consumer-app-version=${{ github.sha }} \
            --branch=${{ github.ref_name }} \
            --broker-base-url=$PACT_BROKER_BASE_URL \
            --broker-token=$PACT_BROKER_TOKEN

  provider_verification:
    runs-on: ubuntu-latest
    needs: consumer_tests
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Verify provider against broker
        env:
          # use mesma key em todo o workflow para evitar confusão
          PACT_BROKER_BASE_URL: '${{ secrets.PACT_BROKER_BASE_URL }}'
          PACT_BROKER_TOKEN: '${{ secrets.PACT_BROKER_TOKEN }}'
        run: |
          pytest tests/test_provider_glpi.py::test_verify_against_broker -q
