# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Performance Check

on:
  pull_request:

jobs:
  performance-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Adiciona a URL base da API para que o build do frontend funcione.
      NEXT_PUBLIC_API_BASE_URL: 'http://localhost:8000'
    steps:
      - uses: actions/checkout@v4
      - name: Configure GitHub CLI
        # This step executes the external shell script to configure GitHub access.
        # It's important to call the script this way to avoid YAML syntax errors
        # that can occur when inlining complex scripts.
        run: bash scripts/setup/setup_github_access.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: src/frontend/react_app/package-lock.json

      - name: Install deps & build
        run: |
          cd src/frontend/react_app
          npm ci --no-audit --progress=false
          npm run build

      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: './src/frontend/react_app/lighthouseci.config.js'
          uploadArtifacts: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
